// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjjtuaguwnjagjakjmiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqanR1YWd1d25qYWdqYWtqbWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTE1MzIsImV4cCI6MjA2MTU2NzUzMn0.b-Tqd8uwvRgUla7e526jJJvF0vtAlKRYzlxLSCd20lM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);